# Generated by Django 2.1 on 2018-08-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_portlog_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='circuit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='network',
            field=models.GenericIPAddressField(null=True, protocol='IPv4'),
        ),
        migrations.AddField(
            model_name='host',
            name='secretary',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
