# Generated by Django 3.0.3 on 2020-04-23 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_auto_20180823_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Host')),
            ],
        ),
        migrations.CreateModel(
            name='Fibra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('dio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Dio')),
            ],
        ),
    ]
