# Generated by Django 3.0.3 on 2020-04-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0010_dio_fibra'),
    ]

    operations = [
        migrations.AddField(
            model_name='fibra',
            name='port',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
