# Generated by Django 3.0.3 on 2020-04-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0012_auto_20200423_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fibra',
            name='port',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
