# Generated by Django 3.1.3 on 2020-11-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0013_auto_20200428_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipv4', models.GenericIPAddressField(protocol='IPv4')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
