# Generated by Django 3.1.3 on 2020-11-20 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0014_network'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Network',
        ),
    ]
