# Generated by Django 3.2.13 on 2022-05-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0015_delete_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='max_retries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='host',
            name='retries',
            field=models.IntegerField(default=0),
        ),
    ]
