# Generated by Django 4.1 on 2022-08-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0017_rename_secretary_host_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='error_counter',
            field=models.BigIntegerField(default=0),
        ),
    ]
