# Generated by Django 4.1.1 on 2022-09-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0018_alter_port_error_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='switch_manager',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
