# Generated by Django 4.1.1 on 2022-09-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0019_host_switch_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='switch_manager',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
