# Generated by Django 4.0.4 on 2023-01-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0020_alter_host_switch_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='max_retries',
            field=models.IntegerField(default=1),
        ),
    ]
