# Generated by Django 4.1.5 on 2023-01-26 16:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0022_alter_dio_id_alter_fibra_id_alter_host_id_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Fibra",
            new_name="Fiber",
        ),
    ]
